require tag_examples module where it's used
Otherwise it's specs would be loaded / run out of context leading to
many errors like this:

  1) Error:
TagExamples::from empty db::lowest_common_ancestor#test_0009_is itself for single item:
NameError: uninitialized class variable @@described_class in TagExamples
Did you mean?  describe
    /closure_tree/test/support/tag_examples.rb:10:in `block (2 levels) in <module:TagExamples>'

when trying to run a single test, i.e.

bundle exec rake test TESTOPTS="--seed=10410" TEST=test/closure_tree/parallel_test.rb